services:
  nginx:
    container_name: nginx
    image: owasp/modsecurity:nginx
    restart: always
    volumes:
      - ./config/nginx/certs:/etc/nginx/certs
      - ./config/nginx/modsecurity:/etc/modsecurity
      - ./config/nginx/modsecurity.d/include.conf:/etc/modsecurity.d/include.conf
      - ./config/nginx/modsecurity.d/modsecurity.conf:/etc/modsecurity.d/modsecurity.conf
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.template
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./apps/cdn-app:/usr/share/nginx/html/cdn
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx-network
    environment:
      - SERVERNAME=localhost
    command: /bin/bash -c "envsubst '$$SERVERNAME' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  bind9:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind9
    restart: always
    ports:
      - "10.0.0.11:53:53/tcp"
      - "10.0.0.11:53:53/udp"
    volumes:
      - "./config/bind9/named.conf:/etc/bind/named.conf"
      - "./config/bind9/named.conf.local:/etc/bind/named.conf.local"
      - "./config/bind9/named.conf.options:/etc/bind/named.conf.options"
      - "./config/bind9/db.powerzio.net:/etc/bind/db.powerzio.net"
  bank-app:
    container_name: bank-app
    build:
      context: .
      dockerfile: config/bank-app/Dockerfile
    restart: always
    volumes:
      - ./apps/bank-app:/var/www/bank.powerzio.net
    networks:
      - nginx-network
  wall-app:
    container_name: wall-app
    build:
      context: .
      dockerfile: config/wall-app/Dockerfile
    restart: always
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
