services:
  nginx:
    image: owasp/modsecurity-crs:nginx-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/templates/conf.d/default.conf.template
      - ./config/nginx/certs:/etc/nginx/certs
      - ./apps/cdn-app:/usr/share/nginx/html/cdn
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      - nginx-network
    environment:
      - PARANOIA=4
      - MODSEC_RULE_ENGINE=On

networks:
  nginx-network:
    driver: bridge
