services:
  traefik:
    image: traefik:v3.2
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.filename=/etc/traefik/dynamic_conf.yml"
      - "--entrypoints.websecure.http.tls=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config/traefik/certs:/certs"
      - "./config/traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`3.35.47.238`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
  bind9:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind9
    restart: always
    ports:
      - "10.0.0.11:53:53/tcp"
      - "10.0.0.11:53:53/udp"
    volumes:
      - "./config/bind9/named.conf:/etc/bind/named.conf"
      - "./config/bind9/named.conf.local:/etc/bind/named.conf.local"
      - "./config/bind9/named.conf.options:/etc/bind/named.conf.options"
      - "./config/bind9/db.powerzio.net:/etc/bind/db.powerzio.net"
    networks:
      - bind9-network
  bank-app:
    container_name: bank-app
    build:
      context: .
      dockerfile: config/bank-app/Dockerfile
    restart: always
    volumes:
      - ./apps/bank-app:/var/www/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bankapp.rule=Host(`bank.powerzio.net`)"
      - "traefik.http.routers.bankapp.entrypoints=web"
      - "traefik.http.services.bankapp.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik-network"
    networks:
      - traefik-network

networks:
  traefik-network:
    driver: bridge
  bind9-network:
    driver: bridge