services:
  bank-app:
    container_name: bank-app
    build:
      context: .
      dockerfile: config/bank-app/Dockerfile
    restart: always
    volumes:
      - ./apps/bank-app:/var/www/app
    ports:
      - "10.0.0.11:8080:5000"