http:
  routers:
    bankapp-router-http:
      rule: "Host(`bank.powerzio.net`)"
      entryPoints:
        - web
      service: bankapp-service
      middlewares:
        - redirect-to-https
    bankapp-router-https:
      rule: "Host(`bank.powerzio.net`)"
      entryPoints:
        - websecure
      service: bankapp-service
      tls: {}
    wallapp-router-http:
      rule: "Host(`wall.powerzio.net`)"
      entryPoints:
        - web
      service: wallapp-service
      middlewares:
        - redirect-to-https
    wallapp-router-https:
      rule: "Host(`wall.powerzio.net`)"
      entryPoints:
        - websecure
      service: wallapp-service
      tls: {}
    cdnapp-router-http:
      rule: "Host(`cdn.powerzio.net`)"
      entryPoints:
        - web
      service: cdnapp-service
      middlewares:
        - redirect-to-https
    cdnapp-router-https:
      rule: "Host(`cdn.powerzio.net`)"
      entryPoints:
        - websecure
      service: cdnapp-service
      tls: {}
    gfapp-router-http:
      rule: "Host(`admin.powerzio.net`)"
      entryPoints:
        - web
      service: gf-service

  services:
    bankapp-service:
      loadBalancer:
        servers:
          - url: "http://bank-app:5000"
    wallapp-service:
      loadBalancer:
        servers:
          - url: "http://wall-app:80"
    cdnapp-service:
      loadBalancer:
        servers:
          - url: "http://cdn-app:80"
    gf-service:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

tls:
  certificates:
    - certFile: "/certs/bank.crt"
      keyFile: "/certs/bank.key"
    - certFile: "/certs/wall.crt"
      keyFile: "/certs/wall.key"
    - certFile: "/certs/cdn.crt"
      keyFile: "/certs/cdn.key"