http:
  routers:
    bankapp-router-http:
      rule: "Host(`bank.powerzio.net`)"
      entryPoints:
        - web
      service: bankapp-service
      middlewares:
        - redirect-to-https
    bankapp-router-https:
      rule: "Host(`bank.powerzio.net`)"
      entryPoints:
        - websecure
      service: bankapp-service
      tls: {}
    
    wallapp-router-http:
      rule: "Host(`wall.powerzio.net`)"
      entryPoints:
        - web
      service: wallapp-service
      middlewares:
        - redirect-to-https
    wallapp-router-https:
      rule: "Host(`wall.powerzio.net`)"
      entryPoints:
        - websecure
      service: wallapp-service
      tls: {}

  services:
    bankapp-service:
      loadBalancer:
        servers:
          - url: "http://bank-app:5000"
    wallapp-service:
      loadBalancer:
        servers:
          - url: "http://wall-app:80"

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

tls:
  certificates:
    - certFile: "/certs/bank.crt"
      keyFile: "/certs/bank.key"
    - certFile: "/certs/wall.crt"
      keyFile: "/certs/wall.key"