http:
  routers:
    bankapp-router-http:
      rule: "Host(`bank.powerzio.net`)"
      entryPoints:
        - web
      service: bankapp-service
      middlewares:
        - redirect-to-https
    bankapp-router-https:
      rule: "Host(`bank.powerzio.net`)"
      entryPoints:
        - websecure
      service: bankapp-service
      tls:
        domains:
          - main: "bank.powerzio.net"
    wallapp-router-http:
      rule: "Host(`wall.powerzio.net`)"
      entryPoints:
        - web
      service: wallapp-service
      middlewares:
        - redirect-to-https
    wallapp-router-https:
      rule: "Host(`wall.powerzio.net`)"
      entryPoints:
        - websecure
      service: wallapp-service
      tls:
        domains:
          - main: "wall.powerzio.net"
    cdnapp-router-http:
      rule: "Host(`cdn.powerzio.net`)"
      entryPoints:
        - web
      service: cdnapp-service
      middlewares:
        - redirect-to-https
    cdnapp-router-https:
      rule: "Host(`cdn.powerzio.net`)"
      entryPoints:
        - websecure
      service: cdnapp-service
      tls:
        domains:
          - main: "cdn.powerzio.net"

  services:
    bankapp-service:
      loadBalancer:
        servers:
          - url: "http://bank-app:5000"
    wallapp-service:
      loadBalancer:
        servers:
          - url: "http://wall-app:80"
    cdnapp-service:
      loadBalancer:
        servers:
          - url: "http://cdn-app:80"

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

tls:
  certificates:
    - certFile: "/certs/bank.powerzio.net.crt"
      keyFile: "/certs/bank.powerzio.net.key"
    - certFile: "/certs/wall.powerzio.net.crt"
      keyFile: "/certs/wall.powerzio.net.key"
    - certFile: "/certs/cdn.powerzio.net.crt"
      keyFile: "/certs/cdn.powerzio.net.key"